### PR TITLE
Comment Extractor.py

### PR DESCRIPTION
**Pull request by hmajid2301**
Added comments to make the `extractor.py` easier to follow. 

Is this what you were looking for ? I Wasn't a 100% sure.

Thanks

### CODE REVIEW

**Comment by marshalmiller** [comment]
This is exactly what I was looking for. Thank you.

**Comment by hmajid2301** [comment]
I dont think this was merged. This was just closed FYI :)

**Comment by hmajid2301** [comment]
I think you can re-open and merge it in.

**Comment by marshalmiller** [comment]
I'm aware. I'm running a test to make sure you get hacktoberfest credit before I merge yours. I don't want you to have done this without proper credit. Thank you, though. I'll merge it right now.

**Comment by hmajid2301** [comment]
ahh ok no worries :) thanks

**Pull request merged**
